int main()
{
	try
	{
		// your code here
		// throw an exception if there is an error
	}
	catch (type_of_the_exception e)
	{
		// catch and handle the exception
	}
}